components:
  schemas:
    controller.AuthorizeRequest:
      properties:
        code:
          type: string
      type: object
    lobbylgc.LobbyState:
      properties:
        players:
          items:
            $ref: '#/components/schemas/model.User'
          type: array
          uniqueItems: false
        spectators:
          items:
            $ref: '#/components/schemas/model.User'
          type: array
          uniqueItems: false
      type: object
    model.User:
      properties:
        accent_color:
          type: integer
        avatar:
          type: string
        banner:
          type: string
        bot:
          type: boolean
        discriminator:
          type: string
        email:
          type: string
        flags:
          type: integer
        global_name:
          type: string
        id:
          type: string
        locale:
          type: string
        mfa_enabled:
          type: boolean
        premium_type:
          type: integer
        public_flags:
          type: integer
        system:
          type: boolean
        username:
          type: string
        verified:
          type: boolean
      type: object
  securitySchemes:
    bearerauth:
      bearerFormat: JWT
      scheme: bearer
      type: http
externalDocs:
  description: ""
  url: ""
info:
  title: ""
  version: ""
openapi: 3.1.0
paths:
  /info:
    get:
      description: return information about the server build, version, etc ...
      responses:
        "200":
          content:
            application/json:
              schema:
                type: struct
            image/png:
              schema:
                format: binary
                type: string
          description: Information about server
      summary: Get server info
      tags:
      - info
  /tile/{name}:
    get:
      description: handles reading an SVG, scaling it, and serving it as a PNG
      parameters:
      - description: Target width in pixels
        in: query
        name: in
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                type: file
            image/png:
              schema:
                format: binary
                type: string
          description: The scaled PNG image
        "400":
          content:
            application/json:
              schema:
                type: string
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                type: string
          description: Image not found
        "500":
          content:
            application/json:
              schema:
                type: string
          description: "Internal Server Error\"/\t@Param\tname\tin\tpath\tstring\ttrue\t\"SVG
            file name"
      summary: Get mahjong tile image
      tags:
      - image
  /token:
    post:
      description: discord oauth2 scheema for authorization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/controller.AuthorizeRequest'
        description: Data for authorization
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Authorizes with discord api
      tags:
      - oauth2
  /ws/game/{userId}/{clientId}:
    get:
      description: Web socket for lobby providing data for players
      responses:
        "500":
          description: Internal Server Error
      summary: web socket for lobby
      tags:
      - lobby
  /ws/lobby/{userId}/{clientId}:
    get:
      description: Web socket for lobby providing data for players
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lobbylgc.LobbyState'
          description: OK
        "500":
          description: Internal Server Error
      summary: web socket for lobby
      tags:
      - lobby
